# Generated by Django 5.0.14 on 2025-04-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('price_per_liter', models.DecimalField(decimal_places=3, max_digits=8)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'ProductPrices',
                'managed': True,
            },
        ),
    ]
