# Generated by Django 5.0.14 on 2025-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('reading_no', models.CharField(db_column='Reading No_', max_length=50, primary_key=True, serialize=False)),
                ('store_no', models.CharField(db_column='Store No_', max_length=50)),
                ('status', models.IntegerField(db_column='Status')),
                ('posted_datetime', models.DateTimeField(db_column='Posted DateTime')),
                ('work_date', models.DateField(db_column='Work Date')),
                ('shift_no', models.IntegerField(db_column='Shift No_')),
            ],
            options={
                'db_table': '[Emarat Misr$Meter Reading]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeterReadingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_no', models.CharField(db_column='Reading No_', max_length=50)),
                ('store_no', models.CharField(db_column='Store No_', max_length=50)),
                ('fuel_item_type', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calibration_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '[Emarat Misr$Meter Reading Lines]',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
