# Generated by Django 5.0.14 on 2025-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=20, unique=True)),
                ('store_name', models.CharField(max_length=100)),
                ('historical_storecode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
