# Generated by Django 5.0.14 on 2025-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasolineProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('historical_productcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
