# Generated by Django 5.0.14 on 2025-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_gasolineproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_code', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('pump_id', models.IntegerField()),
                ('hose_id', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ppu', models.DecimalField(decimal_places=3, max_digits=10)),
                ('money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade_id', models.IntegerField()),
                ('product', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'HistoricalData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionsDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_code', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('pump_id', models.IntegerField()),
                ('hose_id', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ppu', models.DecimalField(decimal_places=3, max_digits=10)),
                ('money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade_id', models.IntegerField()),
                ('product', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TransactionsDetails',
                'managed': True,
            },
        ),
    ]
