# Generated by Django 5.0.14 on 2025-04-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_alter_transactionsdetails_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsdetails',
            name='transBatchID',
            field=models.CharField(default='01-2009-2022-09-02', max_length=50),
        ),
    ]
