# Generated by Django 5.0.14 on 2025-04-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_transactionsdetails_transbatchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('autoID', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('store_id', models.CharField(max_length=20)),
                ('meterReadingNo', models.CharField(max_length=100)),
                ('shiftNo', models.CharField(blank=True, max_length=20, null=True)),
                ('productCode', models.CharField(blank=True, max_length=20, null=True)),
                ('totalVolume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calcVolume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('numberOfRecords', models.IntegerField(blank=True, null=True)),
                ('dateTimeRunOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactionsdetails',
            name='shift',
            field=models.IntegerField(default=1),
        ),
    ]
