# Generated by Django 5.0.14 on 2025-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_transactionlog_transactionsdetails_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='historical_storecode',
        ),
        migrations.AddField(
            model_name='store',
            name='first_shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='first_shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='g80',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='g92',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='g95',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='go',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='latest_used_Receipt',
            field=models.CharField(blank=True, default='000201-P00000000001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='second_shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='second_shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shiftNumb',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='third_shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='third_shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsdetails',
            name='receiptNo',
            field=models.CharField(default='000201-P00000000001', max_length=50),
        ),
    ]
