# Generated by Django 5.0.14 on 2025-05-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_rename_transbatchid_transactionsdetails_meterreading_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='shiftNumb',
            new_name='shiftcount',
        ),
    ]
