# Generated by Django 5.0.14 on 2025-05-04 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_remove_store_first_shift_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsdetails',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transactionsdetails',
            name='is_adjustment',
            field=models.BooleanField(default=False),
        ),
    ]
