# Generated by Django 5.0.14 on 2025-05-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_transactionsdetails_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionsdetails',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
