# Generated by Django 5.0.14 on 2025-05-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0013_rename_create_at_transactionsdetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsdetails',
            name='grade_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsdetails',
            name='hose_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsdetails',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsdetails',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsdetails',
            name='ppu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsdetails',
            name='pump_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsdetails',
            name='shift',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsdetails',
            name='station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
