# Generated by Django 5.0.14 on 2025-05-07 13:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0014_alter_transactionsdetails_grade_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationDailyClosedPeriods',
            fields=[
                ('incrID', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.store', to_field='store_id')),
            ],
        ),
    ]
